/*
CREATE TABLE department (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title varchar not null
);
*/
/*CREATE SEQUENCE department_generator
CREATE TABLE department ( id bigint GENERATED BY DEFAULT AS SEQUENCE department_generator PRIMARY KEY, title varchar(128) NOT NULL CHECK (name <> '') );*/
/*CREATE TABLE department (
   id INT NOT NULL AUTO_INCREMENT,
   title VARCHAR(50) NOT NULL,
   PRIMARY KEY (id)
);*/
INSERT INTO department(title) VALUES('testo1', 'testo2');

